from .nodes.lazy_latent import (
    NODE_CLASS_MAPPINGS as _LAZY_LATENT_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LAZY_LATENT_NAMES,
)
from .nodes.pad_crop import (
    NODE_CLASS_MAPPINGS as _PAD_CROP_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _PAD_CROP_NAMES,
)
from .nodes.parse import (
    NODE_CLASS_MAPPINGS as _PARSE_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _PARSE_NAMES,
)
from .nodes.lazy_load import (
    NODE_CLASS_MAPPINGS as _LAZY_LOAD_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LAZY_LOAD_NAMES,
)
from .nodes.audio import (
    NODE_CLASS_MAPPINGS as _AUDIO_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _AUDIO_NAMES,
)
from .nodes.tensor_tools import (
    NODE_CLASS_MAPPINGS as _TENSOR_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _TENSOR_NAMES,
)
from .nodes.ideogram4 import (
    NODE_CLASS_MAPPINGS as _IDEOGRAM4_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _IDEOGRAM4_NAMES,
)
from .nodes.json_tools import (
    NODE_CLASS_MAPPINGS as _JSON_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _JSON_NAMES,
)

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(_LAZY_LATENT_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_LAZY_LATENT_NAMES)
NODE_CLASS_MAPPINGS.update(_PAD_CROP_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_PAD_CROP_NAMES)
NODE_CLASS_MAPPINGS.update(_PARSE_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_PARSE_NAMES)
NODE_CLASS_MAPPINGS.update(_LAZY_LOAD_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_LAZY_LOAD_NAMES)
NODE_CLASS_MAPPINGS.update(_AUDIO_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_AUDIO_NAMES)
NODE_CLASS_MAPPINGS.update(_TENSOR_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_TENSOR_NAMES)
NODE_CLASS_MAPPINGS.update(_IDEOGRAM4_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_IDEOGRAM4_NAMES)
NODE_CLASS_MAPPINGS.update(_JSON_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_JSON_NAMES)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
