from .nodes.lazy_latent import (
    NODE_CLASS_MAPPINGS as _LAZY_LATENT_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LAZY_LATENT_NAMES,
)
from .nodes.pad_crop import (
    NODE_CLASS_MAPPINGS as _PAD_CROP_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _PAD_CROP_NAMES,
)

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(_LAZY_LATENT_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_LAZY_LATENT_NAMES)
NODE_CLASS_MAPPINGS.update(_PAD_CROP_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_PAD_CROP_NAMES)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
